-- Comments in SQL Start with dash-dash --
-- products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('chair', 44.00, false)
-- products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('stool', 25.99, true)
-- products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('table', 124.00, false)
-- SELECT name FROM products
-- SELECT name, price FROM products
-- products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('stable', 12400.00, false)
-- products_db=# SELECT * FROM products WHERE price > 44.00;
-- products_db=# SELECT * FROM products WHERE price BETWEEN 22.50 AND 99.99
-- products_db=# UPDATE products SET price = price-20;
-- products_db=# DELETE FROM products products_db-# WHERE price < 25 products_db-# SELECT * FROM products
-- products_db=# DELETE FROM products WHERE price < 25;
-- products_db=# UPDATE products SET price = price+20;
-- products_db=# UPDATE products SET can_be_returned = true;